version: '3'

services:

  db:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=nsac2023-demo
    volumes:
      - ./db_backups:/backups
      - pgdata:/var/lib/postgresql/data
    networks:
      - nsac2023

  python:
    # Configuración del servicio del proyecto python 
    build: 
      context: .
      dockerfile: docker_files/python/Dockerfile
    container_name: python-container
    volumes:
      - ./python_app:/app
      - ./python_app/venv:/app/venv
      - ./python_app/.env:/app/.env
      - ./wait-for-it.sh:/app/wait-for-it.sh
    ports:
      - "8000:8000"
    networks:
      - nsac2023
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]

  react:
    build:
      context: .
      dockerfile: docker_files/react/Dockerfile
    container_name: react-container
    volumes:
      - ./react_app:/app
      - ./react_app/node_modules:/app/node_modules
    ports:
      - "5173:5173"
    networks:
      - nsac2023
    depends_on:
      - python

volumes:
  pgdata:

networks:
  nsac2023:
    driver: bridge
